language: generic
sudo: required
services:
  - docker

# build docker image before running the test
before_install:
  - docker build -t stan56/react-test -f ./client/Dockerfile.dev ./client

# run the test suite
# CI option added for test to exit on completion instead of waiting for input
script:
  - docker run -e CI=true stan56/react-test npm test

# after test completes successfully
after_success:
  # build prod images
  - docker build -t stan56/multi-client ./client
  - docker build -t stan56/multi-nginx ./nginx
  - docker build -t stan56/multi-server ./server
  - docker build -t stan56/multi-worker ./worker
  # log in to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push prod images to Docker Hub
  - docker push stan56/multi-client
  - docker push stan56/multi-nginx
  - docker push stan56/multi-server
  - docker push stan56/multi-worker

# deploy to AWS Beanstalk
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-508593366803"
  bucket_path:  "docker-multi"
  # specify GitHub branch to deploy from
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY